development:
  host: 127.0.0.1
  port: 27017
  database: ppn-spider-dev
  #proxy_database: proxy
  #analysis_database:  ppn_development

production:
  host: 10.10.10.1
  port: 27027
  database: qspider-production
